version: '3'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - OAUTH_APP_NAME
      - OAUTH_APP_ID
      - OAUTH_APP_SECRET
      - OAUTH_ACCESS_TOKEN
      - OAUTH_REFRESH_TOKEN
      - SERVICE_PRINCIPAL_TENANT
      - SERVICE_PRINCIPAL_USERNAME
      - SERVICE_PRINCIPAL_PASSWORD
      - TEST_SUBSCRIPTION_ID
